### PR TITLE
Updated Design

### PR DESCRIPTION
**Pull request by varshith15**
- Separate Node Class to store all the node configs
- Updated Quorum Class to move all the configs to node class

### CODE REVIEW

**Comment by Essoz** [comment]
This is a huge change!
The new OOP design is much more cleaner than the previous one! I see how slooo is truly becoming a python library lol😂.  

I have a few questions, 
- will the slow_inject functions be integrated into the `Quorum` class? Or should the user use `Quorum.get_leader()`  or `Quorum.get_follower` to get the node instance and manage slow_injection on their own?

- Why is benchmark_load a Quorum method while the benchmark info is a per-node thing?
- ...

I have a few questions like these because I am not sure about what the specific functionality of each member function is given there are few comments. We should keep a record of the design by adding more comments / documentation. So that we can both understand and analyze the design.

**Comment by Essoz** [comment]
I think for generality, we should generalize things into different classes for generality. Currently, there are too many specific member fields in the node class and things can get coupled easily.
 
For example, for the deployment platform, we are not only targeting at Azure, but also want to let slooo be compatible with GCP and local mode right (all proposed by Tianyin)? Henceforce, I think rather than having the Azure specific fields https://github.com/xlab-uiuc/slooo_internal/blob/updated_design/utils/node.xsh#L10 hardcoded in `node` class, we can implement a `Deploy` class that can be easily inherited to adapt to different platforms and let this class be a member of `node`.

**Comment by varshith15** [comment]
> For example, for the deployment platform, we are not only targeting at Azure, but also want to let slooo be compatible with GCP and local mode right (all proposed by Tianyin)? 

I agree, We can call it azure_configs instead 
for now lets not worry about it, its should be a pretty basic chage

**Comment by Essoz** [comment]
I have a question
:
For cdf graphs, which trial's latency data should be chosen?

**Comment by varshith15** [comment]
@Essoz We could take any one of the trial. Do you have any other idea regarding this?
Can we combine all of the trials? Is that a right way to do?

**Comment by Essoz** [comment]
In the assignment, I actually combined latency data from all trials to draw the CDF graphs. This is a long overdue question, and I am not sure whether this is good enough either.

**Comment by varshith15** [comment]
@Essoz can you check the latest commit. I've revamped a lot of stuff, Need your thoughts. 
Lets get to the CDF combining later.

Just write the code to plot CDF, Let's figure out if we should be combining them later.

**Comment by Essoz** [comment]
I think the refactored structure looks good for now. I will continue to write the CDF plotting function.

**Comment by varshith15** [comment]
@Essoz Need your help in refactoring faults code just like cpu_slow update i did. 
Basically we also send in slowness to the function as well, currently the slowness is hard coded, I need you to update the code for rest of the faults.

Most the updates we thought of are done. Just testing is left from my side, if your plotting functionlity is done, Ill integrate it, Please let me know.

**Comment by Essoz** [comment]
Sure, I completed the code refactoring and will push the CDF functionality. I may need your help with testing the refactored code.

The `node.run` function will also have to be refactored so that stdout and stderr are captured.

**Comment by varshith15** [comment]
I will test the refactored code @Essoz

**Pull request merged**
